Adicionando um md referente ao comando 'git stash'
SDEscobedo/referencia-rapida-git pull request #12
Opened 2023-09-05 14:31 UTC by Guss00

## Criei um arquivo md referente ao comando `git stash`, gostaria que revisasse.

### O arquivo esta no commit 574ae36d67825c6d9f35d902e4d5e329f27b0d52

2023-09-05 18:01 UTC, SDEscobedo requested changes

2023-09-05 18:01 UTC, SDEscobedo commented on commands/gitstash.md
> +Isso retornará uma lista de seus instantâneos salvos no formato `stash@{0}: BRANCH-PARA-A-QUAL-SÃO-AS-ALTERAÇÕES-EM-STASH: MESSAGE`. A parte do `stash@{0}` é o nome do stash, enquanto o número entre
O mesmo vale para todos os parágrafos. [fonte](https://www.freecodecamp.org/portuguese/news/git-stash-explicado-como-armazenar-temporariamente-alteracoes-locais-no-git/).
Uma forma prática é jogar o texto no ChatGPT e pedir para escrever de outro jeito.

2023-09-06 11:29 UTC, Guss00 commented on commands/gitstash.md
> +Isso retornará uma lista de seus instantâneos salvos no formato `stash@{0}: BRANCH-PARA-A-QUAL-SÃO-AS-ALTERAÇÕES-EM-STASH: MESSAGE`. A parte do `stash@{0}` é o nome do stash, enquanto o número entre
## tudo bem, irei refazer aqui

2023-09-06 11:49 UTC, Guss00 commented
## Fiz uma atualização conforme a revisão e gostaria de comentários
### commit: f1755721c8f51557615e5958042aeb42fa3cf5b5

@SDEscobedo

2023-09-06 14:31 UTC, merged